### ISSUE TITLE
Back button in browser is not working correctly

### ISSUE THREAD

**Issue by Lowcase** [Geaz/SharpDox.Plugins.Html#16] opened 2015-04-01 07:03 UTC
I am navigating through the help documentation and visit pages 1, 2 and ended on page 3. Now when I click on back button in the browser, it takes me from page 3 to page 2. When I click on back button again, it takes me from page 2 back to page 3. But I would expect to be on page 1.

It seems like the current page is added to the history every time when url is changed. So by clicking on back button I am not going back but cycling between last two visited pages.

**Comment by Geaz** [comment] 2015-04-01 15:56
Hi, could you please specify how you are navigating (Home->Type->Article->Type etc.)?
Because from my point of view everthing is working like intended.

**Comment by Lowcase** [comment] 2015-04-02 06:22
On http://doc.sharpdox.de/ I am on Home -> Introduction -> Supported documentation tags -> Create advanced documentation -> Create exporter. Now when I am clicking on back button it is taking me from Create exporter to Supported documentation tags -> Create exporter -> Supported documentation tags -> Create exporter -> Supported documentation tags -> Create exporter. I would expect to be taken to Supported documentation tags -> Introduction -> Home -> page where I was before I go to http://doc.sharpdox.de/.

Also the browser's forward button is always disabled. It looks like you are adding page to the history every time the location is changed and therefore it is not possible to go back.

**Comment by Geaz** [comment] 2015-04-02 07:02
Please tell me which browser you are using. I am using FireFox and the back navigation is working like expected.

**Comment by Lowcase** [comment] 2015-04-02 07:08
I am using Chrome.

**Comment by Geaz** [comment] 2015-04-02 16:05
Was able to reproduce the bug with Chrome. WIll look into this issue for the next release.

**Comment by Geaz** [comment] 2015-07-25 07:14
Fixed in new html exporter - will release it soon.

**Closed by Geaz** 2015-07-25 07:14 UTC
Labels: bug
